version: '3.8'


services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: flat_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - flats_postgresql_volume:/var/lib/postgresql

  flat-service:
    build: .
    image: flat-service-image
    container_name: flat-service
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    env_file:
      - .env
    ports:
      - "80:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  flats_postgresql_volume:
