spring:
  profiles:
    default: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    livereload:
      enabled: false

jwt:
  secret: vXBYJAXpsiMo6UUQsaeVztvjyQ/vwlHi+mXRb30dadf1H8SbZ38NfUXW2r01Sn2T
  lifetime: 30m