spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flats_db
    username: root
    password: root

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info

dataRefreshRate: PT60S
